# ------------------------------------------------------------------------
# Quartus Prime Pro project script - minimal UART bring-up build
# Target board: Arrow AXC3000 (Agilex 3 A3CY100BM16AE7S)
#
# Scope: fpga_communication UART block + a 100 MHz IOPLL + an FP32
# fused multiply-add DSP.
#
# VHDL sources live under source/ : hVHDL_uart, hVHDL_fpga_interconnect
# and hVHDL_floating_point are submodules; the three fpga_communication
# glue files are vendored (see source/fpga_communication/README.md).
#
# First checkout:
#     git submodule update --init
#
# Build (run every command from this directory):
#     quartus_sh   -t build_uart_bringup.tcl
#     qsys-generate ip/pll_100/pll_100.ip         --synthesis=VHDL --part=A3CY100BM16AE7S
#     qsys-generate ip/native_fp32/native_fp32.ip --synthesis=VHDL --part=A3CY100BM16AE7S
#     quartus_syn uart_bringup
#     quartus_fit uart_bringup
#     quartus_sta uart_bringup
#     quartus_asm uart_bringup
#
# Program (cable INDEX, not name):
#     quartus_pgm -c 1 -m jtag -o "p;output_files/uart_bringup.sof"
#
# Talk to it (100e6 / 868 ~= 115200 baud, 32-bit data words):
#     python test_hw.py COM<x> 115200
#     >>> uart.request_data_from_address(1)   # -> 44252  (0x0000ACDC)
# ------------------------------------------------------------------------

package require ::quartus::project

variable this_file_path [file dirname [file normalize [info script]]]

set need_to_close_project 0

if {[is_project_open]} {
    if {[string compare $quartus(project) "uart_bringup"]} {
        puts "Project uart_bringup is not open"
        exit 1
    }
} else {
    if {[project_exists uart_bringup]} {
        project_open -revision uart_bringup uart_bringup
    } else {
        project_new -revision uart_bringup uart_bringup
    }
    set need_to_close_project 1
}

# ---------------------------------------------------------------- device
set_global_assignment -name FAMILY "Agilex 3"
set_global_assignment -name DEVICE A3CY100BM16AE7S
set_global_assignment -name TOP_LEVEL_ENTITY uart_bringup_top
set_global_assignment -name ORIGINAL_QUARTUS_VERSION 25.3.0
set_global_assignment -name LAST_QUARTUS_VERSION "25.3.0 Pro Edition"
set_global_assignment -name PROJECT_OUTPUT_DIRECTORY output_files
set_global_assignment -name MIN_CORE_JUNCTION_TEMP 0
set_global_assignment -name MAX_CORE_JUNCTION_TEMP 100
set_global_assignment -name ERROR_CHECK_FREQUENCY_DIVISOR 256
set_global_assignment -name VHDL_INPUT_VERSION VHDL_2019
set_global_assignment -name OPTIMIZATION_MODE BALANCED
set_global_assignment -name BOARD default

# AXC3000 configuration scheme (matches the Arrow NIOSV_lab)
set_global_assignment -name USE_CONF_DONE SDM_IO16
set_global_assignment -name USE_INIT_DONE SDM_IO0

# ------------------------------------------------------------ source set
# fpga_interconnect protocol (generic package + 32 data / 16 address instance)
set_global_assignment -name VHDL_FILE $this_file_path/source/hVHDL_fpga_interconnect/fpga_interconnect_generic_pkg.vhd
set_global_assignment -name VHDL_FILE $this_file_path/source/fpga_communication/fpga_interconnect_16bit_pkg.vhd

# uart rx / tx (entity + package in the same file) and the serial protocol
set_global_assignment -name VHDL_FILE $this_file_path/source/hVHDL_uart/uart_rx/uart_rx_pkg.vhd
set_global_assignment -name VHDL_FILE $this_file_path/source/hVHDL_uart/uart_tx/uart_tx_pkg.vhd
set_global_assignment -name VHDL_FILE $this_file_path/source/fpga_communication/serial_protocol_generic_pkg.vhd
set_global_assignment -name VHDL_FILE $this_file_path/source/fpga_communication/communications.vhd

# git hash constant (refresh with ./write_githash.ps1)
set_global_assignment -name VHDL_FILE $this_file_path/git_hash_pkg.vhd

# FP32 fused multiply-add - same hVHDL_floating_point module the full build uses
set_global_assignment -name VHDL_FILE $this_file_path/source/hVHDL_floating_point/vhdl2008/float_typedefs_generic_pkg.vhd
set_global_assignment -name VHDL_FILE $this_file_path/source/hVHDL_floating_point/vhdl2008/multiply_add_entity.vhd
set_global_assignment -name VHDL_FILE $this_file_path/source/hVHDL_floating_point/vhdl2008/altera/multiply_add_arch_agilex.vhd

# float -> fixed-point conversion: the float_to_fixed entity (abstract
# interface, multiply_add style; hfloat ref + pipeline depth are generics,
# radix travels in the request record).  Needs float_typedefs_generic_pkg
# (added above for the FMA).
set_global_assignment -name VHDL_FILE $this_file_path/float_to_fixed.vhd

# bring-up top level
set_global_assignment -name VHDL_FILE $this_file_path/uart_bringup_top.vhd

# ------------------------------------------------------------------- IP
# 25 MHz clk_clk -> 100 MHz core_clock (generated by ip-deploy altera_iopll)
set_global_assignment -name IP_FILE $this_file_path/ip/pll_100/pll_100.ip
# FP32 native hard-float DSP (fp32_mult_add)
set_global_assignment -name IP_FILE $this_file_path/ip/native_fp32/native_fp32.ip

# ---------------------------------------------------------- constraints
set_global_assignment -name SDC_FILE $this_file_path/uart_bringup.sdc

# ------------------------------------------------------------------ pins
# from Arrow AXC3000 NIOSV_lab/completed_lab/NIOSV_lab.qsf
set_location_assignment PIN_A7   -to clk_clk       -comment IOBANK_3A_B
set_location_assignment PIN_A12  -to reset_reset_n -comment IOBANK_3A_B
set_location_assignment PIN_AG23 -to uart_rxd      -comment IOBANK_5A
set_location_assignment PIN_AG24 -to uart_txd      -comment IOBANK_5A

# Arduino MKR header D4..D7 (see docs/mkr_pinout.md)
set_location_assignment PIN_AF19 -to mkr_d4        -comment IOBANK_5A
set_location_assignment PIN_AG20 -to mkr_d5        -comment IOBANK_5A
set_location_assignment PIN_AK19 -to mkr_d6        -comment IOBANK_5B
set_location_assignment PIN_AJ19 -to mkr_d7        -comment IOBANK_5A

set_instance_assignment -name IO_STANDARD "1.3-V LVCMOS" -to clk_clk       -entity uart_bringup_top
set_instance_assignment -name IO_STANDARD "1.3-V LVCMOS" -to reset_reset_n -entity uart_bringup_top
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to uart_rxd      -entity uart_bringup_top
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to uart_txd      -entity uart_bringup_top
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to mkr_d4        -entity uart_bringup_top
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to mkr_d5        -entity uart_bringup_top
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to mkr_d6        -entity uart_bringup_top
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to mkr_d7        -entity uart_bringup_top

set_instance_assignment -name WEAK_PULL_UP_RESISTOR ON -to reset_reset_n -entity uart_bringup_top
set_instance_assignment -name CURRENT_STRENGTH_NEW 6MA -to uart_txd      -entity uart_bringup_top
set_instance_assignment -name CURRENT_STRENGTH_NEW 6MA -to mkr_d4        -entity uart_bringup_top
set_instance_assignment -name CURRENT_STRENGTH_NEW 6MA -to mkr_d5        -entity uart_bringup_top
set_instance_assignment -name CURRENT_STRENGTH_NEW 6MA -to mkr_d6        -entity uart_bringup_top
set_instance_assignment -name CURRENT_STRENGTH_NEW 6MA -to mkr_d7        -entity uart_bringup_top

# --------------------------------------------------------------- commit
export_assignments

if {$need_to_close_project} {
    project_close
}
