# ------------------------------------------------------------------------
# Quartus Prime Pro project script - minimal UART bring-up build
# Target board: Arrow AXC3000 (Agilex 3 A3CY100BM16AE7S)
#
# Scope: source/fpga_communication UART block + a 100 MHz IOPLL.
#
# The PLL IP was created with:
#   ip-deploy --component-name=altera_iopll --output-name=pll_100 \
#     --output-directory=ip/pll_100 --family="Agilex 3" --part=A3CY100BM16AE7S \
#     --component-parameter=gui_reference_clock_frequency=25.0 \
#     --component-parameter=gui_number_of_clocks=1 \
#     --component-parameter=gui_output_clock_frequency0=100.0 \
#     --component-parameter=gui_use_locked=true
# quartus_syn regenerates the IP HDL from the .ip file automatically.
#
# Create / update the project:
#     quartus_sh -t build_uart_bringup.tcl
#
# Compile from the command line:
#     quartus_syn uart_bringup
#     quartus_fit uart_bringup
#     quartus_asm uart_bringup
#     quartus_sta uart_bringup
#
# Program:
#     quartus_pgm -m jtag -o "p;output_files/uart_bringup.sof"
#
# Program (cable INDEX, not name):
#     quartus_pgm -c 1 -m jtag -o "p;output_files/uart_bringup.sof"
#
# Talk to it (25e6 / 217 ~= 115200 baud, 32-bit data words):
#     python ../test_hw.py COM<x> 115200
#     >>> uart.request_data_from_address(1)   # -> 44252  (0x0000ACDC)
#
# Run every command from this axc3000/ directory.
# ------------------------------------------------------------------------

package require ::quartus::project

variable this_file_path [file dirname [file normalize [info script]]]
variable repo_root [file normalize $this_file_path/..]

set need_to_close_project 0

if {[is_project_open]} {
    if {[string compare $quartus(project) "uart_bringup"]} {
        puts "Project uart_bringup is not open"
        exit 1
    }
} else {
    if {[project_exists uart_bringup]} {
        project_open -revision uart_bringup uart_bringup
    } else {
        project_new -revision uart_bringup uart_bringup
    }
    set need_to_close_project 1
}

# ---------------------------------------------------------------- device
set_global_assignment -name FAMILY "Agilex 3"
set_global_assignment -name DEVICE A3CY100BM16AE7S
set_global_assignment -name TOP_LEVEL_ENTITY uart_bringup_top
set_global_assignment -name ORIGINAL_QUARTUS_VERSION 25.3.0
set_global_assignment -name LAST_QUARTUS_VERSION "25.3.0 Pro Edition"
set_global_assignment -name PROJECT_OUTPUT_DIRECTORY output_files
set_global_assignment -name MIN_CORE_JUNCTION_TEMP 0
set_global_assignment -name MAX_CORE_JUNCTION_TEMP 100
set_global_assignment -name ERROR_CHECK_FREQUENCY_DIVISOR 256
set_global_assignment -name VHDL_INPUT_VERSION VHDL_2019
set_global_assignment -name OPTIMIZATION_MODE BALANCED
set_global_assignment -name BOARD default

# AXC3000 configuration scheme (matches the Arrow NIOSV_lab)
set_global_assignment -name USE_CONF_DONE SDM_IO16
set_global_assignment -name USE_INIT_DONE SDM_IO0

# ------------------------------------------------------------ source set
# fpga_interconnect protocol (generic package + 32 data / 16 address instance)
set_global_assignment -name VHDL_FILE $repo_root/source/fpga_communication/hVHDL_fpga_interconnect/fpga_interconnect_generic_pkg.vhd
set_global_assignment -name VHDL_FILE $repo_root/source/fpga_communication/fpga_interconnect_16bit_pkg.vhd

# uart rx / tx (entity + package in the same file) and the serial protocol
set_global_assignment -name VHDL_FILE $repo_root/source/fpga_communication/hVHDL_uart/uart_rx/uart_rx_pkg.vhd
set_global_assignment -name VHDL_FILE $repo_root/source/fpga_communication/hVHDL_uart/uart_tx/uart_tx_pkg.vhd
set_global_assignment -name VHDL_FILE $repo_root/source/fpga_communication/serial_protocol_generic_pkg.vhd
set_global_assignment -name VHDL_FILE $repo_root/source/fpga_communication/communications.vhd

# git hash constant (generated by ../write_githash.ps1)
set_global_assignment -name VHDL_FILE $repo_root/git_hash_pkg.vhd

# FP32 fused multiply-add - same module as ../quartus_pro (build_agilex_3)
set_global_assignment -name VHDL_FILE $repo_root/source/hVHDL_floating_point/vhdl2008/float_typedefs_generic_pkg.vhd
set_global_assignment -name VHDL_FILE $repo_root/source/hVHDL_floating_point/vhdl2008/multiply_add_entity.vhd
set_global_assignment -name VHDL_FILE $repo_root/source/hVHDL_floating_point/vhdl2008/altera/multiply_add_arch_agilex.vhd

# bring-up top level
set_global_assignment -name VHDL_FILE $this_file_path/uart_bringup_top.vhd

# ------------------------------------------------------------------- IP
# 25 MHz clk_clk -> 100 MHz core_clock (generated by ip-deploy altera_iopll)
set_global_assignment -name IP_FILE $this_file_path/ip/pll_100/pll_100.ip
# FP32 native hard-float DSP (fp32_mult_add) - copied from ../quartus_pro/ip
set_global_assignment -name IP_FILE $this_file_path/ip/native_fp32/native_fp32.ip

# ---------------------------------------------------------- constraints
set_global_assignment -name SDC_FILE $this_file_path/uart_bringup.sdc

# ------------------------------------------------------------------ pins
# from Arrow AXC3000 NIOSV_lab/completed_lab/NIOSV_lab.qsf
set_location_assignment PIN_A7   -to clk_clk       -comment IOBANK_3A_B
set_location_assignment PIN_A12  -to reset_reset_n -comment IOBANK_3A_B
set_location_assignment PIN_AG23 -to uart_rxd      -comment IOBANK_5A
set_location_assignment PIN_AG24 -to uart_txd      -comment IOBANK_5A

set_instance_assignment -name IO_STANDARD "1.3-V LVCMOS" -to clk_clk       -entity uart_bringup_top
set_instance_assignment -name IO_STANDARD "1.3-V LVCMOS" -to reset_reset_n -entity uart_bringup_top
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to uart_rxd      -entity uart_bringup_top
set_instance_assignment -name IO_STANDARD "3.3-V LVCMOS" -to uart_txd      -entity uart_bringup_top

set_instance_assignment -name WEAK_PULL_UP_RESISTOR ON -to reset_reset_n -entity uart_bringup_top
set_instance_assignment -name CURRENT_STRENGTH_NEW 6MA -to uart_txd      -entity uart_bringup_top

# --------------------------------------------------------------- commit
export_assignments

if {$need_to_close_project} {
    project_close
}
